# Netlify configuration for Vite + React
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
